Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,32 +8,32 @@ jobs:
 
   Windows:
     runs-on: windows-latest
-    timeout-minutes: 9999
+    # timeout-minutes: 9999
 
     steps:
-    - name: Download files.
-      run: |
-        Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/ngrok.exe -OutFile D:\a\_temp\ngrok.exe
-        Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/NGROK-AP.bat -OutFile D:\a\_temp\NGROK-AP.bat
-        Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/user-create.bat -OutFile D:\a\_temp\user-create.bat
-        Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/info.bat -OutFile D:\a\_temp\info.bat
-        Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/loop.bat -OutFile D:\a\_temp\loop.bat
-    - name: Connect your NGROK account.
-      run: | 
-        D:\a\_temp\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
-      env:
-        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
-    - name: Enable RDP Access.
-      run: | 
-        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
-        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
-        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
-    - name: Create Tunnel.
-      run: Start-Process -FilePath "D:\a\_temp\ngrok.exe" -ArgumentList "tcp 3389 -region ${{ secrets.NGROK_REGION }}"
-    - name: Create user account.
-      run: cmd /c D:\a\_temp\user-create.bat
-    - name: VM Info.
-      run: cmd /c D:\a\_temp\info.bat
+    # - name: Download files.
+    #   run: |
+    #     Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/ngrok.exe -OutFile D:\a\_temp\ngrok.exe
+    #     Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/NGROK-AP.bat -OutFile D:\a\_temp\NGROK-AP.bat
+    #     Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/user-create.bat -OutFile D:\a\_temp\user-create.bat
+    #     Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/info.bat -OutFile D:\a\_temp\info.bat
+    #     Invoke-WebRequest https://github.com/cationx/GitHub-Action-RDP/raw/main/Windows/loop.bat -OutFile D:\a\_temp\loop.bat
+    # - name: Connect your NGROK account.
+    #   run: | 
+    #     D:\a\_temp\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
+    #   env:
+    #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
+    # - name: Enable RDP Access.
+    #   run: | 
+    #     Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
+    #     Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
+    #     Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
+    # - name: Create Tunnel.
+    #   run: Start-Process -FilePath "D:\a\_temp\ngrok.exe" -ArgumentList "tcp 3389 -region ${{ secrets.NGROK_REGION }}"
+    # - name: Create user account.
+    #   run: cmd /c D:\a\_temp\user-create.bat
+    # - name: VM Info.
+    #   run: cmd /c D:\a\_temp\info.bat
     
     - run: git config --global core.autocrlf input
       shell: bash
@@ -70,39 +70,22 @@ jobs:
       run: |
         pacman --noconfirm -U msys2/*.zst
 
-    - name: Debugging
-      shell: msys2 {0}
-      if: success() || failure()
-      run: |
-        export
-        echo ls -----------
-        ls /mingw64/bin
-        echo ldd ---------------
-        ldd /mingw64/bin/glscopeclient.exe
-
-
-    - name: Debugging 2
+    - name: Test
       if: success() || failure()
       shell: msys2 {0}
       continue-on-error: true
       run: |
         glscopeclient.exe --help 
 
-    - name: Screenshot
-      if: success() || failure()
-      uses: OrbitalOwen/desktop-screenshot-action@0.1
-      with:
-        file-name: 'desktop.jpg'
+    # - name: Screenshot
+    #   if: success() || failure()
+    #   uses: OrbitalOwen/desktop-screenshot-action@0.1
+    #   with:
+    #     file-name: 'desktop.jpg'
 
-    - name: Debugging 3
-      shell: msys2 {0}
-      if: success() || failure()
-      run: |
-        'glscopeclient --help 2>&1 | tee gl2.log'
-        'glscopeclient.exe 2>&1 | tee gl3.log'
 
-    - name: Keep your VM alive.
-      run: cmd /c D:\a\_temp\loop.bat
+    # - name: Keep your VM alive.
+    #   run: cmd /c D:\a\_temp\loop.bat
 
     - name: Upload Artifacts (logs 1)
       if: success() || failure()
@@ -123,13 +106,6 @@ jobs:
           -DWIXPATH="/c/Program Files (x86)/WiX Toolset v3.11/bin" \
           ../
         VULKAN_SDK=C:/VulkanSDK/1.3.216.0 cmake --build ./
-
-
-    - name: Upload Artifacts (logs 2)
-      uses: actions/upload-artifact@v2
-      with:
-        name: logs
-        path: ./*.log
 
     - name: Upload Artifacts (portable zip)
       uses: actions/upload-artifact@v2
